Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2018-10, with the labels that each got.

#241 Travis - change postgres to 9.5
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes

#242 Add ConfigPattern class and type
  app/models/manageiq/providers/lenovo/physical_infra_manager/config_pattern.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/config_pattern_parser.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
Labels: enhancement

#236 Graph refresh
  app/models/manageiq/providers/lenovo/inventory.rb
  app/models/manageiq/providers/lenovo/inventory/collector.rb
  app/models/manageiq/providers/lenovo/inventory/collector/physical_infra_manager.rb
  app/models/manageiq/providers/lenovo/inventory/parser.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/canister.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/compliance_policy.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/computer_system.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/config_pattern.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/firmware.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/guest_device.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/management_device.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/network_device.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/physical_chassis.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/physical_disk.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/physical_network_port.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/physical_rack.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/physical_server.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/physical_storage.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/physical_switch.rb
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/storage_device.rb
  app/models/manageiq/providers/lenovo/inventory/parser/physical_infra_manager.rb
  app/models/manageiq/providers/lenovo/inventory/persister.rb
  app/models/manageiq/providers/lenovo/inventory/persister/definitions/physical_infra_collections.rb
  app/models/manageiq/providers/lenovo/inventory/persister/physical_infra_manager.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/hardware.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresher.rb
  config/settings.yml
Labels: enhancement

#244 fix the firmware parse of guest device
  app/models/manageiq/providers/lenovo/inventory/parser/component_parser/guest_device.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/guest_device_parser.rb
Labels: bug
