Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2018-04, with the labels that each got.

#147 Parsing physical rack
  app/models/manageiq/providers/lenovo/physical_infra_manager.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_rack_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_server_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser_dictionary_constants.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parsers.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/physical_rack.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
Labels: enhancement

#153 [Changelog] Update for Sprint 83
  CHANGELOG.md
Labels: documentation

#155 [GAPRINDASHVILI] [BZ 1563796] Fixing the network devices and ports parser
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Labels: blocker

#154 Remove require_relative and fix autoload class names
  app/models/manageiq/providers/lenovo/physical_infra_manager.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/config_pattern_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/network_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_rack_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/storage_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/component_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/config_pattern_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/network_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_rack_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_server_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/storage_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser_dictionary_constants.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parsers.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Labels: technical debt

#132 Adding parsing steps for switches
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/firmware_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/network_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/storage_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/physical_switch.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/full_refresh.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/mock_switches.yml
Labels: enhancement

#142 Parsing pci_device and vlan info to ports
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/network_device_parser.rb
Labels: wip

#163 [Changelog] Update for Sprint 84
  CHANGELOG.md
Labels: documentation
