Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2018-09, with the labels that each got.

#183 Moved common dictionary constants to component parser (#7)
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/network_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/storage_device_parser.rb
Labels: refactoring

#222 Moving location_led_state to Asset Detail
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
Labels: gaprindashvili/no, refactoring

#184 Move dictionary constants to respective parser (#8)
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/config_pattern_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/firmware_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_network_ports_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_rack_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
Labels: refactoring

#187 Extract management device parser (#10)
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/management_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
Labels: refactoring

#188 Organizing existing parsers (#11)
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
Labels: refactoring

#227 [Changelog] Update for Sprint 94
  CHANGELOG.md
Labels: documentation

#189 Adds support for computed properties on parser mapping (#12)
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/firmware_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/management_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_network_ports_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
Labels: refactoring, unmergeable

#190 Extract a GuestDeviceParser superclass from storage and network (#13)
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/component_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/guest_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/network_device_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/storage_device_parser.rb
Labels: refactoring

#192 Extract tests from Physical Infra Manager tests (#14)
  spec/models/manageiq/providers/lenovo/manager_mixin_spec.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/authenticatable_provider_spec.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/operations_spec.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager_spec.rb
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/authenticatable_provider/change_password_with_invalid_new_password.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/authenticatable_provider/change_password_with_invalid_password.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/authenticatable_provider/change_password_with_valid_password.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/blink_loc_led.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/power_off.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/power_off_now.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/power_on.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/restart.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/restart_mgmt_controller.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/restart_now.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/restart_to_sys_setup.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/turn_off_loc_led.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/operations/turn_on_loc_led.yml
Labels: refactoring, unmergeable

#228 Fix the timeout param
  app/models/manageiq/providers/lenovo/manager_mixin.rb
Labels: bug, gaprindashvili/no

#230 [Changelog] Update for Sprint 95
  CHANGELOG.md
Labels: documentation

#231 [HAMMER] [Changelog] Update for Hammer Beta-1 release
  CHANGELOG.md
Labels: documentation
