Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2018-03, with the labels that each got.

#140 Fixing bug in the calculate of physical server total memory
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
Labels: bug, gaprindashvili/yes

#139 Refactoring the parse structure
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/component_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/config_pattern_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_server_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parser_dictionary_constants.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/parsers.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Labels: refactoring

#141 Leaving the disk capacity blank if the LXCA doesn't provide this information
  app/models/manageiq/providers/lenovo/physical_infra_manager/parsers/components/physical_server_parser.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
Labels: enhancement, gaprindashvili/yes

#146 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation
