Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2018-08, with the labels that each got.

#215 [Changelog] Update for Sprint 91
  CHANGELOG.md
Labels: documentation

#214 Add provisioning support to Lenovo::PhysicalInfraManager
  app/models/manageiq/providers/lenovo/physical_infra_manager.rb
Labels: bug

#219 [Changelog] Update for Sprint 92
  CHANGELOG.md
Labels: documentation

#181 Fix all rubocop issues (#5)
  .rubocop_local.yml
  app/models/manageiq/providers/lenovo/manager_mixin.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_worker.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresher.rb
  app/models/manageiq/providers/lenovo/provider.rb
  lib/tasks/lenovo.rake
  spec/spec_helper.rb
Labels: refactoring, unmergeable
