Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2018-07, with the labels that each got.

#196 [Changelog] Update for Sprint 87
  CHANGELOG.md
Labels: documentation

#206 [Changelog] Update for Sprint 89
  CHANGELOG.md
Labels: documentation

#208 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-4
  CHANGELOG.md
Labels: documentation

#194 Parsing the connection b/w ports
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_network_ports_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/full_refresh.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/mock_switches.yml
Labels: enhancement

#201 Adding parser for PhysicalStorage inside PhysicalChassis
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/mock_cabinet.yml
Labels: enhancement

#211 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation

#212 Fixing error while try to generate the physical switch port uuid
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_network_ports_parser.rb
Labels: bug
