Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2018-06, with the labels that each got.

#193 [Changelog] Update for Sprint 86
  CHANGELOG.md
Labels: documentation

#170 Parse Physical Storage
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/parser_dictionary_constants.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/physical_storage.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/full_refresh.yml
  spec/vcr_cassettes/manageiq/providers/lenovo/physical_infra_manager/mock_cabinet.yml
Labels: enhancement

#173 Remove ipaddress and hostname updates from physical_infra_manager (#1)
  app/models/manageiq/providers/lenovo/physical_infra_manager.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Labels: refactoring

#178 Use local variable to return inventory (#2)
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/config_pattern_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_chassis_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_rack_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_server_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_storage_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/parser/physical_switch_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
Labels: refactoring

#179 Removing RefreshHelperMethods unused code (#3)
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
  app/models/manageiq/providers/lenovo/refresh_helper_methods.rb
Labels: refactoring
