Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2019-10, with the labels that each got.

#280 Remove to_json from toolbar data as it's not needed
  app/helpers/manageiq/providers/lenovo/toolbar_overrides/ems_physical_infra_center.rb
Labels: ivanchuk/no

#281 Toolbar update
  app/helpers/manageiq/providers/lenovo/toolbar_overrides/ems_physical_infra_center.rb
Labels: ivanchuk/no

#284 Remove zanata from README
  README.md
Labels: cleanup

#283 Remove zanata.xml
  zanata.xml
Labels: cleanup

#282 Test ruby 2.5.7/2.6.5, see: ManageIQ/manageiq#19414
  .travis.yml
Labels: test
