Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2019-11, with the labels that each got.

#287 Add params_for_create and verify_credentials
  app/models/manageiq/providers/lenovo/manager_mixin.rb
Labels: enhancement

#288 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#289 Rely on the default implementation of .ems_class
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_worker.rb
Labels: refactoring
