Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2020-03, with the labels that each got.

#291 Remove legacy refresh parser
  app/models/manageiq/providers/lenovo/physical_infra_manager.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/refresher.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresh_parser_spec.rb
  spec/models/manageiq/providers/lenovo/physical_infra_manager/refresher_spec.rb
Labels: technical debt

#293 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#294 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#295 remove inventory object refresh from settings
  config/settings.yml
Labels: cleanup

#296 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#297 Remove unused ems_inv_to_hashes method
  app/models/manageiq/providers/lenovo/inventory/parser/physical_infra_manager.rb
  app/models/manageiq/providers/lenovo/refresh_helper_methods.rb
Labels: cleanup
