Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2020-05, with the labels that each got.

#301 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#302 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#299 Remove unused dependency to react-ui-components
  package.json
Labels: cleanup, dependencies
