Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2020-09, with the labels that each got.

#311 Remove executable bit from files that don't need it
  app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/runner.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/event_catcher/stream.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/event_parser.rb
  app/models/manageiq/providers/lenovo/physical_infra_manager/operations.rb
Labels: bug

#310 Update DDF schema to version 2
  app/models/manageiq/providers/lenovo/manager_mixin.rb
Labels: enhancement

#313 Plugin Generator Updates
  .codeclimate.yml
  .gitignore
  .rubocop.yml
  .rubocop_cc.yml
  .travis.yml
  README.md
  Rakefile
  bin/ci/after_script
  bundler.d/.keep
  lib/manageiq/providers/lenovo/engine.rb
  lib/tasks/README.md
  lib/tasks_private/spec.rake
  manageiq-providers-lenovo.gemspec
  spec/spec_helper.rb
Labels: developer

#312 [JANSA] yarn upgrade: upgrade JS dependencies
  yarn.lock
Labels: dependencies, jansa/yes

#314 Make the default credentials required in the provider DDF
  app/models/manageiq/providers/lenovo/manager_mixin.rb
Labels: bug

#315 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/lenovo/manager_mixin.rb
Labels: enhancement
