Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2022-05, with the labels that each got.

#370 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#369 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: test

#373 Remove urijs dependency by using strings for API calls
  app/javascript/components/apply-config-pattern-form-provider.jsx
  app/javascript/components/firmware-update-form-provider.jsx
  package.json
  yarn.lock
Labels: technical debt, dependencies, najdorf/yes?
