Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2022-02, with the labels that each got.

#350 Remove Hakiri
  README.md
Labels: cleanup, developer

#351 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-lenovo.gemspec
Labels: developer, test

#353 Add Build History Graph to README.md
  README.md
Labels: developer, test

#354 fix yarn lock file
  yarn.lock
Labels: test

#345 Update node version
  package.json
Labels: dependencies

#356 Downgrade node version to 14
  .yarn/install-state.gz
  package.json
Labels: dependencies

#357 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
