Repository ManageIQ/manageiq-providers-lenovo, pull requests merged in 2023-04, with the labels that each got.

#383 [WIP] Upgrade Node v14 to v16
  package.json
Labels: wip

#385 Upgrade yarn to 3.5.0
  .yarn/releases/yarn-3.0.2.cjs
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: dependencies

#386 Drop lib/gem-name.rb in favor of lib/gem/name.rb
  lib/manageiq-providers-lenovo.rb
  lib/manageiq/providers/lenovo.rb
  spec/spec_helper.rb
Labels: enhancement
